# https://github.com/actions/runner-images

name: Build

on: [push]

jobs:
  macos_15_sequoia:
    name: macOS 15 Sequoia
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          PATH=$PATH:$PWD
          mkdir build
          cd build
          cmake .. -G Xcode -DUNITS=1
          cmake --build .
      - name: Test
        run: build/Debug/units
